version: "3.8"
services:
  frontend:
    build:
      context: ./
      target: front
    ports:
      - 3000:3000
    depends_on:
      - "backend"
  backend:
    build:
      context: ./
      target: back
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db:27017/user-list
    depends_on:
      - "db"
  db:
    image: mongo:4.4.1
    container_name: db
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_DATABASE: user-list
    restart: 'always'